Fix or suppress ocamlc unused variable/binding warnings
dividat/playos pull request #171
Opened 2024-07-26 06:31 UTC by yfyf

`dune` treats warnings-as-errors by default, so these changes ensure `dune build` works without
`--profile release` (used in [controller/bin/build](https://github.com/dividat/playos/blob/main/controller/bin/build#L7-L9)) i.e. there are no more warnings raised by ocamlc.

## Checklist

-   [ ] Changelog updated
-   [ ] Code documented
-   [ ] User manual updated

2024-07-29 05:24 UTC, knuton requested changes
:+1: Good idea

A couple of suggestions

2024-07-29 09:54 UTC, yfyf commented on controller/server/network.ml
> +let _log_src = Logs.Src.create "network"
Wasn't sure whether this has any side-effects or not, will remove

2024-08-01 09:28 UTC, yfyf commented on controller/server/network.ml
> +let _log_src = Logs.Src.create "network"
Rather than removing this, I updated the log calls to actually use the defined source.

2024-08-01 09:29 UTC, yfyf commented on controller/bindings/disable-unused-warnings.dune
> +; and dune treats these as errors, so we disable them here
Added!

2024-08-01 09:30 UTC, yfyf commented
@knuton pushed changes addressing the comments, please take a look!

2024-08-01 09:43 UTC, knuton commented on controller/server/network.ml
> +let _log_src = Logs.Src.create "network"
That is much better. :-)

2024-08-01 09:53 UTC, knuton approved these changes
Very good, thanks!

2024-08-01 09:53 UTC, merged