Improve install device selection in installer
dividat/playos pull request #182
Opened 2024-09-24 15:15 UTC by yfyf

- Look for "/iso" mount not only in children of blockdevices, but top-level devices too (e.g. this happens when running qemu with `-cdrom playos-installer-<..>.iso`)
- Eliminate devices that are too small or read-only from potential installation targets.

cc @knuton 

## Checklist

-   [X] Changelog updated
-   [ ] Code documented
-   [ ] User manual updated

2024-09-24 15:20 UTC, yfyf commented
P.S. I was "inspired" to do this PR because I was running qemu with `-cdrom playos-installer-XX.iso` and it would fail to identify the mounted ISO as the boot medium (and hence would not filter it out from potential installation targets).

2024-09-24 16:20 UTC, knuton requested changes
Looks good! A few minor suggestions.

2024-09-24 16:20 UTC, knuton commented on controller/Changelog.md
> +- os: Improve install device selection
```suggestion
- os: Improve installation device selection
```

2024-09-24 16:20 UTC, knuton commented on installer/install-playos/install-playos.py
> +        is_boot_device = (boot_device) and (dev.path.startswith(boot_device))
Maybe by being a bit more explicit it's clearer that all devices pass this if the boot device could not be identified:

```suggestion
        is_boot_device = (boot_device is not None) and (dev.path.startswith(boot_device))
```

2024-09-24 16:20 UTC, knuton commented on installer/install-playos/install-playos.py
> +REQUIRED_INSTALL_DEVICE_SIZE_GB = PARTITION_SIZE_GB_DATA + PARTITION_SIZE_GB_SYSTEM + 1
We need room for two system partitions, right?

2024-09-24 16:20 UTC, knuton commented on installer/install-playos/install-playos.py
>      print(f"Found {len(available_devices)} possible installation targets:")
Maybe before this we could print the required disk space, so it's clear why certain devices listed above are not listed below.

2024-09-26 07:42 UTC, yfyf commented on installer/install-playos/install-playos.py
> +        return (not is_boot_device) and (not is_read_only) and (is_big_enough)
To be honest, I just did it without thinking, I guess to keep it symmetric, but it is slightly confusing, will remove.

2024-09-26 08:21 UTC, yfyf commented
Resolved all the comments, tested manually by adding additional disks and checking that it picks the right one based on size:

```
Found 2 disk devices:
        /dev/vdb (Virtio Block Device - 1 GB)
        /dev/vda (Virtio Block Device - 28 GB)
Could not identify installer medium. Considering all disks as installation targets.
Minimum required size for installation target: 26 GB
Found 1 possible installation targets:
        /dev/vda (Virtio Block Device - 28 GB)
```

(Installer medium is not identified because I am running via nix `runInLinuxVM`.

2024-09-26 09:47 UTC, knuton commented
> tested manually by adding additional disks and checking that it picks the right one based on size

Did the following additional sanity checks on physical machine:

- The 32 GB installation medium is ignored
- Additional 8 GB device is ignored
- 120 GB disk is selected

2024-09-26 09:48 UTC, knuton approved these changes
Thanks :ok_hand:

2024-09-26 09:48 UTC, merged